# Generated by Django 6.0.5 on 2026-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeafImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaf_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('moisture_content', models.FloatField(blank=True, help_text='Soil moisture content %', null=True)),
                ('actual_disease', models.CharField(choices=[('angular_leaf_spot', 'Angular Leaf Spot'), ('wildfire', 'Wildfire'), ('healthy', 'Healthy'), ('unknown', 'Unknown')], default='unknown', help_text='Actual/known disease label (for training data)', max_length=50)),
                ('predicted_disease', models.CharField(blank=True, choices=[('angular_leaf_spot', 'Angular Leaf Spot'), ('wildfire', 'Wildfire'), ('healthy', 'Healthy'), ('unknown', 'Unknown')], help_text='AI predicted disease', max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Prediction confidence %', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional observations')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
