# Generated by Django 6.0.5 on 2026-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafimage',
            name='claude_features',
            field=models.TextField(blank=True, help_text='Distinguishing features identified by AI'),
        ),
        migrations.AddField(
            model_name='leafimage',
            name='claude_reasoning',
            field=models.TextField(blank=True, help_text='AI explanation of classification'),
        ),
    ]
